name: Deploy Blog

on: [ push ] # 当有新push时运行

env:
  TZ: Asia/Shanghai

jobs:
  build: # 一项叫做build的任务
    environment: github-pages

    runs-on: ubuntu-latest # 在最新版的Ubuntu系统下运行

    steps:
      - name: Checkout # 将仓库内source分支的内容下载到工作目录
        uses: actions/checkout@v2 # 脚本来自 https://github.com/actions/checkout
        with:
          ref: source
          submodules: recursive

      - name: Setup node
        # 配置Node环境
        uses: actions/setup-node@v1 # 配置脚本来自 https://github.com/actions/setup-node
        with:
          node-version: "16.x"


      - name: Install hexo dependencies
        # 下載 hexo-cli 腳手架及相關安裝包
        run: |
          npm install hexo-cli gulp -g
          npm install
          npm install hexo@6.1.0

      - name: Generate files
        # 編譯 markdown 文件
        run: |
          hexo clean --debug
          hexo generate --debug

      - name: Deploy hexo blog
        env:
          # Github 倉庫
          GITHUB_REPO: github.com/aletnox/aletnox.github.io
        # 將編譯後的博客文件推送到指定倉庫
        run: |
          cd ./public && git init && git add .
          git config user.name "aletnox"
          git config user.email "aletnox@gmail.com"
          git add .
          git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
          # "https://SuCicada:${{ secrets.GITEE_ACCESS_TOKEN }}@${{ env.GITEE_REPO }}"
          # "https://${{ secrets.CODING_ACCESS_TOKEN_USERNAME }}:${{ secrets.CODING_ACCESS_TOKEN }}@${{ env.CODING_REPO }}"
          repos=(
            "https://oauth2:${{ secrets.GITHUB_TOKEN }}@${{ env.GITHUB_REPO }}"
          )
          for repo in ${repos[@]};do
            echo start push $repo
            git push --force --quiet $repo master:master
            echo success push $repo
          done

     